web/config/routes.rb
Web::Application.routes.draw do
  resources :stores

  resources :receipt_items

  get "/my/receipts" => "receipts#index_mine"

  resources :receipts

  post "/receipt" => "receipts#from_text"  

  devise_for :users

  resources :products

  root :to => "products#index"
end

web/app/models/receipt.rb
class Receipt < ActiveRecord::Base
  has_many :receipt_items
  belongs_to :user
  belongs_to :store
  attr_accessible :store, :timestamp, :user_id, :store_id

  def total_amount
    sum = 0
    self.receipt_items.each { |i| sum += i.total }
    sum
  end

  def no_of_items
    self.receipt_items.length
  end
end

web/app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipts }
    end
  end

  def index_mine
    @receipts = current_user.receipts
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipts }
    end
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/new
  # GET /receipts/new.json
  def new
    @receipt = Receipt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipt }
    end
  end

  # post /receipts
  def from_text
    if params[:name].present? && params[:data].present?
      puts params[:data]
      lines = params[:data].split("\n")
      items = []
      lines.each do |a|
        tokens = a.strip().split(" ")
        if tokens.length >= 5
          type = tokens[0]
          name = tokens[1..-4].join(" ")
          quantity = tokens[-3]
          price_per_item = tokens[-2]
          price_total = tokens[-1]
          if is_int?(quantity) && is_int?(price_per_item) && is_int?(price_total)
            items << { 
                :letter => type, 
                :name => name, 
                :quantity => quantity,
                :price => price_per_item,
                :total => price_total
            }
          end
        end
      end
      if items.length > 0
        e = params[:name].gsub("_at_", "@")
        attached_user = User.find_by_email(e)
        if attached_user == nil
          puts 'did not find any user: anonymous'
          r = Receipt.create(:store_id => 1, :timestamp => DateTime.now)
        elsif
          r = Receipt.create(:store_id => 1, :user_id => attached_user.id, :timestamp => DateTime.now)
        end
        r.receipt_items.create(items)
        r.save!
      end
      render :text => 'ok', :status => 200
    else
      render :text => 'you suck', :status => 403
    end
  end

  # GET /receipts/1/edit
  def edit
    @receipt = Receipt.find(params[:id])
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(params[:receipt])

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render json: @receipt, status: :created, location: @receipt }
      else
        format.html { render action: "new" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipts/1
  # PUT /receipts/1.json
  def update
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      if @receipt.update_attributes(params[:receipt])
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to receipts_url }
      format.json { head :no_content }
    end
  end

  private

  def is_int?(x)
    !!(x =~ /^[-+]?[0-9\.]+$/)
  end
end

web/app/helpers/receipts_helper.rb
module ReceiptsHelper
end

web/app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :timestamp %><br />
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :store_id %><br />
    <%= f.text_field :store_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/receipts/edit.html.erb
<h1>Editing receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

web/app/views/receipts/index.html.erb
<h1>Listing receipts</h1>

<table>
  <tr>
    <th>Timestamp</th>
    <th>User</th>
    <th>Store</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receipts.each do |receipt| %>
  <tr>
    <td><%= receipt.timestamp %></td>
    <td><%= receipt.user_id %></td>
    <td><%= receipt.store_id %></td>
    <td><%= link_to 'Show', receipt %></td>
    <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
    <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receipt', new_receipt_path %>

web/app/views/receipts/index_mine.html.erb
<h1>Kvittanirnar þínar</h1>

<table class="pure-table" style="width: 100%;">
  <thead>
  <tr>
    <th>Dagsetning</th>
    <th>Verslun</th>
    <th>Fjöldi vara</th>
    <th>Upphæð samtals</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>

<% if @receipts.length == 0 %>
  <tr><td colspan="7">Engar kvittanir komnar!</td></tr>
<% end %>

<% @receipts.each do |receipt| %>
  <tr>
    <td><%= receipt.timestamp.strftime('%d/%m/%Y') %></td>
    <td><%= receipt.store ? receipt.store.name : 'Óvitað' %></td>
    <td><%= receipt.no_of_items %></td>
    <td><%= receipt.total_amount %></td>
    <td><%= link_to 'Nánar', receipt %></td>
    <td><%= link_to 'Breyta', edit_receipt_path(receipt) %></td>
    <td><%= link_to 'Eyða', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<div style="float: right; ">
<%= link_to 'Búa til nýja kvittun', new_receipt_path, :class => 'pure-button pure-button-primary' %>
</div>

web/app/views/receipts/new.html.erb
<h1>New receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

web/app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Timestamp:</b>
  <%= @receipt.timestamp %>
</p>

<p>
  <b>User:</b>
  <%= @receipt.user_id %>
</p>

<p>
  <b>Store:</b>
  <%= @receipt.store_id %>
</p>

<table class="pure-table">
    <thead>
        <tr>
            <th>Flokkur</th>
            <th>Vöruheiti</th>
            <th>Magn</th>
            <th>Verð/einingu</th>
            <th>Samtals</th>
        </tr>
    </thead>

    <tbody>

<% @receipt.receipt_items.each do |r| %>
    <tr>
        <td><%= r.letter %></td>
        <td><%= r.name %></td>
        <td><%= r.quantity %></td>
        <td><%= r.price %></td>
        <td><%= r.total %></td>
    </tr>
<% end %>

    </tbody>
</table>

<script type="text/javascript">
    $('.saver').click() {}
</script>

<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>