web/config/routes.rb
Web::Application.routes.draw do
  resources :stores

  resources :receipt_items

  get "/my/receipts" => "receipts#index_mine"

  resources :receipts

  post "/receipt" => "receipts#from_text"  

  devise_for :users

  resources :products

  root :to => "products#index"
end

web/app/models/receipt_item.rb
class ReceiptItem < ActiveRecord::Base
  belongs_to :receipt

  attr_accessible :name, :price, :quantity, :receipt_id, :total, :letter
end

web/app/controllers/receipt_items_controller.rb
class ReceiptItemsController < ApplicationController
  # GET /receipt_items
  # GET /receipt_items.json
  def index
    @receipt_items = ReceiptItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipt_items }
    end
  end

  # GET /receipt_items/1
  # GET /receipt_items/1.json
  def show
    @receipt_item = ReceiptItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipt_item }
    end
  end

  # GET /receipt_items/new
  # GET /receipt_items/new.json
  def new
    @receipt_item = ReceiptItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipt_item }
    end
  end

  # GET /receipt_items/1/edit
  def edit
    @receipt_item = ReceiptItem.find(params[:id])
  end

  # POST /receipt_items
  # POST /receipt_items.json
  def create
    @receipt_item = ReceiptItem.new(params[:receipt_item])

    respond_to do |format|
      if @receipt_item.save
        format.html { redirect_to @receipt_item, notice: 'Receipt item was successfully created.' }
        format.json { render json: @receipt_item, status: :created, location: @receipt_item }
      else
        format.html { render action: "new" }
        format.json { render json: @receipt_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipt_items/1
  # PUT /receipt_items/1.json
  def update
    @receipt_item = ReceiptItem.find(params[:id])

    respond_to do |format|
      if @receipt_item.update_attributes(params[:receipt_item])
        format.html { redirect_to @receipt_item, notice: 'Receipt item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receipt_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipt_items/1
  # DELETE /receipt_items/1.json
  def destroy
    @receipt_item = ReceiptItem.find(params[:id])
    @receipt_item.destroy

    respond_to do |format|
      format.html { redirect_to receipt_items_url }
      format.json { head :no_content }
    end
  end
end

web/app/helpers/receipt_items_helper.rb
module ReceiptItemsHelper
end

web/app/views/receipt_items/_form.html.erb
<%= form_for(@receipt_item) do |f| %>
  <% if @receipt_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt_item.errors.count, "error") %> prohibited this receipt_item from being saved:</h2>

      <ul>
      <% @receipt_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :receipt_id %><br />
    <%= f.number_field :receipt_id %>
  </div>
  <div class="field">
    <%= f.label :letter %><br />
    <%= f.text_field :letter %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.number_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/receipt_items/edit.html.erb
<h1>Editing receipt_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt_item %> |
<%= link_to 'Back', receipt_items_path %>

web/app/views/receipt_items/index.html.erb
<h1>Listing receipt_items</h1>

<table>
  <tr>
    <th>Receipt</th>
    <th>Type</th>
    <th>Name</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receipt_items.each do |receipt_item| %>
  <tr>
    <td><%= receipt_item.receipt_id %></td>
    <td><%= receipt_item.letter %></td>
    <td><%= receipt_item.name %></td>
    <td><%= receipt_item.quantity %></td>
    <td><%= receipt_item.price %></td>
    <td><%= receipt_item.total %></td>
    <td><%= link_to 'Show', receipt_item %></td>
    <td><%= link_to 'Edit', edit_receipt_item_path(receipt_item) %></td>
    <td><%= link_to 'Destroy', receipt_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receipt item', new_receipt_item_path %>

web/app/views/receipt_items/new.html.erb
<h1>New receipt_item</h1>

<%= render 'form' %>

<%= link_to 'Back', receipt_items_path %>

web/app/views/receipt_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Receipt:</b>
  <%= @receipt_item.receipt_id %>
</p>

<p>
  <b>Type:</b>
  <%= @receipt_item.letter %>
</p>

<p>
  <b>Name:</b>
  <%= @receipt_item.name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @receipt_item.quantity %>
</p>

<p>
  <b>Price:</b>
  <%= @receipt_item.price %>
</p>

<p>
  <b>Total:</b>
  <%= @receipt_item.total %>
</p>


<%= link_to 'Edit', edit_receipt_item_path(@receipt_item) %> |
<%= link_to 'Back', receipt_items_path %>